import { SynthSettings } from "./types";

export const presets: Record<string, SynthSettings> = {
  "Classic Moog": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: 7,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.4,
        detune: -7,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1000,
      resonance: 0.5,
      contourAmount: 0.5,
      type: "lowpass",
    },
    envelope: {
      attack: 0.1,
      decay: 0.3,
      sustain: 0.7,
      release: 0.5,
    },
    lfo: {
      rate: 5,
      depth: 0.3,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 20,
      decay: 1.5,
      eq: 50,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 0,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Warm Pad": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.3,
    oscillators: [
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 7,
        range: "8",
        volume: 0.5,
        detune: 3,
      },
      {
        waveform: "sine",
        frequency: -7,
        range: "8",
        volume: 0.3,
        detune: -3,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 1,
      contourAmount: 0.3,
      type: "lowpass",
    },
    envelope: {
      attack: 0.5,
      decay: 0.8,
      sustain: 0.8,
      release: 1.2,
    },
    lfo: {
      rate: 2,
      depth: 0.2,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 40,
      decay: 2.5,
      eq: 60,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 20,
      time: 0.4,
      feedback: 0.3,
    },
  },
  "Bass Lead": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.1,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "16",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "16",
        volume: 0.6,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "16",
        volume: 0.3,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 500,
      resonance: 0.3,
      contourAmount: 0.7,
      type: "lowpass",
    },
    envelope: {
      attack: 0.01,
      decay: 0.2,
      sustain: 0.6,
      release: 0.3,
    },
    lfo: {
      rate: 8,
      depth: 0.4,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 10,
      decay: 1.0,
      eq: 40,
    },
    distortion: {
      outputGain: 20,
      lowEQ: 60,
      highEQ: 40,
    },
    delay: {
      amount: 0,
      time: 0.3,
      feedback: 0.3,
    },
  },
  Pluck: {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "square",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 12,
        range: "8",
        volume: 0.4,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 19,
        range: "8",
        volume: 0.2,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 2,
      contourAmount: 0.8,
      type: "lowpass",
    },
    envelope: {
      attack: 0.01,
      decay: 0.1,
      sustain: 0.1,
      release: 0.2,
    },
    lfo: {
      rate: 0,
      depth: 0,
      waveform: "sine",
      routing: {
        filterCutoff: false,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 30,
      decay: 1.0,
      eq: 50,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 15,
      time: 0.2,
      feedback: 0.2,
    },
  },
};
